### ISSUE TITLE
Fullnode doesn't sync from fast sync validator

### ISSUE THREAD

**Issue by paul-serdiuk** [aptos-labs/aptos-ait3#60]
Hello.
My VFN is stuck at zero, restarting it doesn't help:

```
# HELP aptos_mempool_bounded_executor_spawn_latency Time it takes for mempool's coordinator to spawn async tasks
# HELP aptos_state_sync_continuous_syncer_errors Counters related to state sync continuous syncer errors
# TYPE aptos_state_sync_continuous_syncer_errors counter
aptos_state_sync_continuous_syncer_errors{error_label="unexpected_error"} 56894
# HELP aptos_state_sync_executing_component_counters Counters related to the currently executing component
# TYPE aptos_state_sync_executing_component_counters counter
aptos_state_sync_executing_component_counters{label="bootstrapper"} 2
aptos_state_sync_executing_component_counters{label="continuous_syncer"} 203318
# HELP aptos_state_sync_version The versions processed by the storage synchronizer operations
# TYPE aptos_state_sync_version gauge
aptos_state_sync_version{type="applied_transaction_outputs"} 0
aptos_state_sync_version{type="executed_transactions"} 0
aptos_state_sync_version{type="synced"} 0
aptos_state_sync_version{type="synced_epoch"} 1
```

The validator is working fine:
```
# HELP aptos_state_sync_version The versions processed by the storage synchronizer operations
# TYPE aptos_state_sync_version gauge
aptos_state_sync_version{type="applied_transaction_outputs"} 265281128
aptos_state_sync_version{type="executed_transactions"} 293094193
aptos_state_sync_version{type="synced"} 294453928
aptos_state_sync_version{type="synced_epoch"} 146
# HELP aptos_consensus_proposals_count Count of the block proposals sent by this validator since last restart (both primary and secondary)
# TYPE aptos_consensus_proposals_count counter
aptos_consensus_proposals_count 169
```

Connections are there:
validator:
```
aptos_connections{direction="inbound",network_id="vfn",peer_id="00000000",role_type="validator"} 1
aptos_connections{direction="outbound",network_id="vfn",peer_id="00000000",role_type="validator"} 0
```
fullnode:
```
aptos_connections{direction="inbound",network_id="vfn",peer_id="307dd4e0",role_type="full_node"} 0
aptos_connections{direction="outbound",network_id="vfn",peer_id="307dd4e0",role_type="full_node"} 1
aptos_data_client_error_responses{network="vfn",peer_id="00000000",response_type="TOTAL_COUNT"} 275008
aptos_data_client_error_responses{network="vfn",peer_id="00000000",response_type="unexpected_error_encountered"} 275008
aptos_mempool_active_upstream_peers_count{network="vfn"} 1
```

Fullnode logs:
```
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.361169Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672171,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"ERROR","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:413"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.459380Z","data":{"error":{"AptosDataClientError":"Unexpected error encountered: Internal service error: Storage error encountered: No TransactionInfo at version 1"},"event":"error","message":"Encountered a data client error!","name":"received_data_response","stream_id":130519}}
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.460603Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672173,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"ERROR","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:413"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.559981Z","data":{"error":{"AptosDataClientError":"Unexpected error encountered: Internal service error: Storage error encountered: No TransactionInfo at version 1"},"event":"error","message":"Encountered a data client error!","name":"received_data_response","stream_id":130519}}
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.562596Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672175,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"ERROR","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:413"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.659784Z","data":{"error":{"AptosDataClientError":"Unexpected error encountered: Internal service error: Storage error encountered: No TransactionInfo at version 1"},"event":"error","message":"Encountered a data client error!","name":"received_data_response","stream_id":130519}}
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.660891Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672176,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"INFO","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/state.rs:195"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.660897Z","data":{"event":"peer_ignored","message":"Peer will be ignored","name":"peer_states","peer":"vfn:00000000"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:312"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.760269Z","data":{"event":"pending","message":"Sent the end of stream notification","name":"end_of_stream_notification","stream_id":130519}}
{"level":"INFO","source":{"package":"state_sync_driver","file":"state-sync/state-sync-v2/state-sync-driver/src/utils.rs:150"},"thread_name":"state-sync-driver","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.760306Z","data":{"message":"Terminating the data stream with ID: 130519, notification and feedback: Some(NotificationAndFeedback { notification_id: 73625, notification_feedback: EndOfStream })","name":"driver"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:149"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.760336Z","data":{"event":"success","message":"Terminating the data stream with ID: 130519. Notification and feedback: Some(NotificationAndFeedback { notification_id: 73625, notification_feedback: EndOfStream })","name":"handle_terminate_request","stream_id":130519}}
{"level":"INFO","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/state.rs:177"},"thread_name":"aptos-data-client","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.761112Z","data":{"event":"peer_no_longer_ignored","message":"Peer will no longer be ignored","name":"peer_states","peer":"vfn:00000000"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:216"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:03.989952Z","data":{"event":"success","message":"Stream created for request: StreamRequestMessage { stream_request: ContinuouslyStreamTransactionOutputs(ContinuouslyStreamTransactionOutputsRequest { known_version: 0, known_epoch: 1, target: None }), response_sender: Sender { complete: false } }","name":"handle_stream_request","stream_id":130520}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs:704"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.060248Z","data":{"event":"pending","message":"Requested an epoch ending ledger info for epoch: 1","name":"aptos_data_client"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:319"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.060264Z","data":{"event":"success","message":"Data stream initialized.","name":"initialize_stream","stream_id":130520}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs:538"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.160329Z","data":{"event":"success","message":"Received an epoch ending ledger info for epoch: 1. Setting new target version: 3","name":"received_data_response"}}
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.161787Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672181,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"ERROR","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:413"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.260132Z","data":{"error":{"AptosDataClientError":"Unexpected error encountered: Internal service error: Storage error encountered: No TransactionInfo at version 1"},"event":"error","message":"Encountered a data client error!","name":"received_data_response","stream_id":130520}}
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.262346Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672182,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"ERROR","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:413"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.359650Z","data":{"error":{"AptosDataClientError":"Unexpected error encountered: Internal service error: Storage error encountered: No TransactionInfo at version 1"},"event":"error","message":"Encountered a data client error!","name":"received_data_response","stream_id":130520}}
{"level":"ERROR","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:434"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.361845Z","data":{"error":"UnexpectedErrorEncountered(\"Internal service error: Storage error encountered: No TransactionInfo at version 1\")","event":"response_error","name":"storage_service_response","peer":"vfn:00000000","request_id":672184,"request_type":"get_transaction_outputs_with_proof_compressed"}}
{"level":"INFO","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/state.rs:195"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.361858Z","data":{"event":"peer_ignored","message":"Peer will be ignored","name":"peer_states","peer":"vfn:00000000"}}
{"level":"ERROR","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:413"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.460209Z","data":{"error":{"AptosDataClientError":"Unexpected error encountered: Internal service error: Storage error encountered: No TransactionInfo at version 1"},"event":"error","message":"Encountered a data client error!","name":"received_data_response","stream_id":130520}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/data_stream.rs:312"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.559421Z","data":{"event":"pending","message":"Sent the end of stream notification","name":"end_of_stream_notification","stream_id":130520}}
{"level":"INFO","source":{"package":"state_sync_driver","file":"state-sync/state-sync-v2/state-sync-driver/src/utils.rs:150"},"thread_name":"state-sync-driver","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.559463Z","data":{"message":"Terminating the data stream with ID: 130520, notification and feedback: Some(NotificationAndFeedback { notification_id: 73626, notification_feedback: EndOfStream })","name":"driver"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:149"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.559497Z","data":{"event":"success","message":"Terminating the data stream with ID: 130520. Notification and feedback: Some(NotificationAndFeedback { notification_id: 73626, notification_feedback: EndOfStream })","name":"handle_terminate_request","stream_id":130520}}
{"level":"INFO","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/state.rs:177"},"thread_name":"aptos-data-client","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.560285Z","data":{"event":"peer_no_longer_ignored","message":"Peer will no longer be ignored","name":"peer_states","peer":"vfn:00000000"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:216"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.790060Z","data":{"event":"success","message":"Stream created for request: StreamRequestMessage { stream_request: ContinuouslyStreamTransactionOutputs(ContinuouslyStreamTransactionOutputsRequest { known_version: 0, known_epoch: 1, target: None }), response_sender: Sender { complete: false } }","name":"handle_stream_request","stream_id":130521}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs:704"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.860352Z","data":{"event":"pending","message":"Requested an epoch ending ledger info for epoch: 1","name":"aptos_data_client"}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/streaming_service.rs:319"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.860365Z","data":{"event":"success","message":"Data stream initialized.","name":"initialize_stream","stream_id":130521}}
{"level":"INFO","source":{"package":"data_streaming_service","file":"state-sync/state-sync-v2/data-streaming-service/src/stream_engine.rs:538"},"thread_name":"data-streaming-service","hostname":"cc9c0a7eeef8","timestamp":"2022-09-07T19:37:04.959661Z","data":{"event":"success","message":"Received an epoch ending ledger info for epoch: 1. Setting new target version: 3","name":"received_data_response"}}
```

validator.yaml:
```
base:
  role: "validator"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_file: "/opt/aptos/genesis/waypoint.txt"

consensus:
  safety_rules:
    service:
      type: "local"
    backend:
      type: "rocks_db_storage"
      path: secure_storage_db
      namespace: ~
    initial_safety_rules_config:
      from_file:
        waypoint:
          from_file: /opt/aptos/genesis/waypoint.txt
        identity_blob_path: /opt/aptos/genesis/validator-identity.yaml
  quorum_store_poll_count: 1

execution:
  genesis_file_location: "/opt/aptos/genesis/genesis.blob"
  concurrency_level: 4

validator_network:
  discovery_method: "onchain"
  mutual_authentication: true
  identity:
    type: "from_file"
    path: /opt/aptos/genesis/validator-identity.yaml

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  identity:
    type: "from_config"
    key: "b0f405a3e75516763c43a2ae1d70423699f34cd68fa9f8c6bb2d67aa87d0af69"
    peer_id: "00000000000000000000000000000000d58bc7bb154b38039bc9096ce04e1237"

api:
  enabled: true
  address: "0.0.0.0:8080"

state_sync:
  state_sync_driver:
    bootstrapping_mode: DownloadLatestStates
    continuous_syncing_mode: ApplyTransactionOutputs
  data_streaming_service:
    max_concurrent_requests: 8
```

fullnode.yaml:
```
base:
  role: "full_node"
  data_dir: "/opt/aptos/data"
  waypoint:
    from_file: "/opt/aptos/genesis/waypoint.txt"

execution:
  genesis_file_location: "/opt/aptos/genesis/genesis.blob"

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  seeds:
    00000000000000000000000000000000d58bc7bb154b38039bc9096ce04e1237:
      addresses:
      - "/ip4/158.255.76.173/tcp/6181/noise-ik/f0274c2774519281a8332d0bb9d8101bd58bc7bb154b38039bc9096ce04e1237/handshake/0"
      role: "Validator"

- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6182"
  max_inbound_connections: 100
  identity:
    type: "from_file"
    path: "/opt/aptos/genesis/validator-full-node-identity.yaml"

api:
  enabled: true
  address: "0.0.0.0:8080"
```

**Comment by holms2** [comment]
a typical way to solve this problem:
https://discord.com/channels/945856774056083548/1013928987908653128/1016909936170643456

**Comment by paul-serdiuk** [comment]
Yeah, resolved by adding
```
state_sync:
  state_sync_driver:
    bootstrapping_mode: DownloadLatestStates
    continuous_syncing_mode: ApplyTransactionOutputs
  data_streaming_service:
    max_concurrent_requests: 8
```
to fullnode.yaml
